# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('coords', models.CharField(max_length=80)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#885736', max_length=9)),
                ('content', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('geoPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.GeoPoint')),
            ],
        ),
        migrations.AddField(
            model_name='geopoint',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Itinerary'),
        ),
    ]
